language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install codecov pep8
  - python setup.py install
script:
  - coverage run setup.py test
  - pep8 lispify tests --ignore=E501
after_success:
  - codecov
