language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - if [[ $TRAVIS_INSTALL_LIKE_PIP == false ]]; then pip install -r requirements.txt; fi
  - pip install codecov pep8
  - python setup.py install
script:
  - coverage run setup.py test
  - pep8 lispify tests --ignore=E501
after_success:
  - codecov
env:
    - TRAVIS_INSTALL_LIKE_PIP=true
    - TRAVIS_INSTALL_LIKE_PIP=false
