language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install codecov pep8
  - python setup.py install
script:
  - coverage run setup.py test
  - pep8 lispify tests --ignore=E501
after_success:
  - codecov
