language: python
# we test python 2.7 because it is what we use, we test python 3.4
# because it is the version of python3 that we have installed, and
# we test the nightly build to make sure we are all up-to-date
python:
  - "2.7"
  - "3.4"
  - "nightly"
install:
  - if [[ $TRAVIS_INSTALL_LIKE_PIP == false ]]; then pip install -r requirements.txt; fi
  - pip install codecov pep8
  - pip install --upgrade setuptools
  - python setup.py install
script:
  - coverage run setup.py test
  - pep8 lispify tests --ignore=E501
after_success:
  - codecov
env:
    - TRAVIS_INSTALL_LIKE_PIP=true
    - TRAVIS_INSTALL_LIKE_PIP=false
